#-----------------------------------------
# CloudBuild Pipeline for Prod CloudRun
#-----------------------------------------
steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=music-app-cluster'
