version: "3.9"
services:
  identity:
    image: identity
    container_name: identity
    ports:
      - "5000:80"
  identity_db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: identity_db
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Strong_Password0
  songservice:
    image: songservice
    container_name: songservice
    ports:
      - "5001:80"
  songservice_db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: songservice_db
    ports:
      - "1434:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Strong_Password0