apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\rediska\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --file C:\Users\rediska\source\repos\MusicApp\docker-compose.yml --out C:\Users\rediska\source\repos\MusicApp\k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\rediska\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --file C:\Users\rediska\source\repos\MusicApp\docker-compose.yml --out C:\Users\rediska\source\repos\MusicApp\k8s
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/musicapp-default: "true"
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: rediska235/apigateway:latest
          name: apigateway
          ports:
            - containerPort: 80
              hostPort: 5003
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
