apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rediska\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --file C:\Users\rediska\source\repos\MusicApp\docker-compose.yml --out C:\Users\rediska\source\repos\MusicApp\k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
  namespace: default
spec:
  selector:
    io.kompose.service: apigateway
  ports:
    - name: "5003"
      port: 5003
      targetPort: 80
  type: LoadBalancer
