apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rediska\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --file C:\Users\rediska\source\repos\MusicApp\docker-compose.yml --out C:\Users\rediska\source\repos\MusicApp\k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: playlistservice
  name: playlistservice
  namespace: default
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 80
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    io.kompose.service: playlistservice
status:
  loadBalancer: {}
