apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\rediska\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --file C:\Users\rediska\source\repos\MusicApp\docker-compose.yml --out C:\Users\rediska\source\repos\MusicApp\k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: songservice-db
  name: songservice-db
  namespace: default
spec:
  ports:
    - name: "1434"
      port: 1434
      targetPort: 1433
  selector:
    io.kompose.service: songservice-db
status:
  loadBalancer: {}
