apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\rediska\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --file C:\Users\rediska\source\repos\MusicApp\docker-compose.yml --out C:\Users\rediska\source\repos\MusicApp\k8s
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: songservice-db
  name: songservice-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: songservice-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\rediska\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert --file C:\Users\rediska\source\repos\MusicApp\docker-compose.yml --out C:\Users\rediska\source\repos\MusicApp\k8s
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/musicapp-default: "true"
        io.kompose.service: songservice-db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "y"
            - name: SA_PASSWORD
              value: Strong_Password0
          image: mcr.microsoft.com/mssql/server:2022-latest
          name: songservice-db
          ports:
            - containerPort: 1433
              hostPort: 1434
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
